name: test
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  test:
    name: Run Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        nvim_version: [nightly, 'v0.10.4']
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.nvim_version }}

      - uses: leafo/gh-actions-lua@v11
        with:
          luaVersion: "luajit-openresty"
      - uses: leafo/gh-actions-luarocks@v5

      - name: Install vusted
        run: |
          luarocks install busted --only-server https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/daab2726276e3282dc347b89a42a5107c3500567
          luarocks --lua-version=5.1 install vusted

      - name: Run test
        run: vusted ./test
